[package]
name = "rgrep"
version = "0.1.0"
authors = ["Serkan Ã–zel <serkanozel380@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
